### ISSUE TITLE
Vasile Popa

### ISSUE THREAD

**Issue by popovvasile** [WorldBrain/TEAM#31]
Hi! My name is Vasile

Hi! My (**GitHub nick**)name is popovvasile

Now I am working on scrapy spiders and I am trying to solve the problem with multi-threading using celery

**Comment by oliversauter** [comment]
Hey Vasile, thanks for adding yourself, please use the template provided though :)

To the bottom from here: 



### Hi! My name is...

_your name - Please name the issue the same way_

### Hi! My (**GitHub nick**)name is...
_@your-nick_

### You can reach me here...

_Skype, Email, Bongo drums_
(Optional but very helpful)

### This is the city and time zone I am mostly in...

_your city/timezone_

### I am currently available...
 - [ ] Not until mm/dd/yyyy and then...
 - [ ] ___ hour(s) per **Week**
 - [ ] ___ hour(s) per **Month**
 - [ ] irregular, only on request
 - [ ] other: 

### I consider it to fun to...

_IDEAS: poke my nose (in nature), play piano naked on city roofs, invent crazy things that somehow become alife_

### I want to contribute to WorldBrain because...

_IDEAS: What impact you want to have? What is exciting about this project?_

### I regularly use these languages and frameworks:

| Languages/Frameworks/Technologies  | Level (1=apprentice to 5=wizard)  |
|---|---|
|   |   |
|   |   |
|   |   |
|   |   |
|   |   |
|   |   |
|   |   |
|   |   |



### In the next year, I want to learn...

_Any languages, frameworks or techniques you want to learn and where we can help you?_
